import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export function Iphone12pro({ color, rotation }, props) {
  const ref = useRef(null);
  useFrame(() => (ref.current.rotation.y += rotation ? 0.01 : 0));

  const { nodes, materials } = useGLTF('/apple/iphone_12_pro.glb');
  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, -2.4, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, Math.PI, 0]} scale={5}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_PacificBlue_0.geometry}
              material-color={color}
              material={materials.PacificBlue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_GrayGlossy_0.geometry}
              material-color={color}
              material={materials.GrayGlossy}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_FrontCamera_0.geometry}
              material-color={color}
              material={materials.FrontCamera}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_Blackmatte_0.geometry}
              material-color={color}
              material={materials.Blackmatte}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_Glass_0.geometry}
              material-color={color}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera1_Cameralens_0.geometry}
              material-color={color}
              material={materials.Cameralens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Flash_Flash2_0.geometry}
              material-color={color}
              material={materials.Flash2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Flash_Flash_0.geometry}
              material-color={color}
              material={materials.Flash}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.LiDar_LiDar__0.geometry}
              material-color={color}
              material={materials.LiDar}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontCamera_FrontCamera_0.geometry}
              material-color={color}
              material={materials.FrontCamera}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontCamera_Glass_0.geometry}
              material-color={color}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontCamera_Cameralens_0.geometry}
              material-color={color}
              material={materials.Cameralens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontMic_GrayGlossy2_0.geometry}
              material-color={color}
              material={materials.GrayGlossy2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry}
              material-color={color}
              material={materials.MicrophoneSpeaker}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.FrontCamera001_bezel001_0.geometry}
              material-color={color}
              material={materials['bezel.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Bezel_bezel_0.geometry}
              material-color={color}
              material={materials.bezel}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_PacificBlue_0.geometry}
              material-color={color}
              material={materials.PacificBlue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_GrayGlossy_0.geometry}
              material-color={color}
              material={materials.GrayGlossy}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_FrontCamera_0.geometry}
              material-color={color}
              material={materials.FrontCamera}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_Blackmatte_0.geometry}
              material-color={color}
              material={materials.Blackmatte}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_Glass_0.geometry}
              material-color={color}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera3_Cameralens_0.geometry}
              material-color={color}
              material={materials.Cameralens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_PacificBlue_0.geometry}
              material-color={color}
              material={materials.PacificBlue}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_GrayGlossy_0.geometry}
              material-color={color}
              material={materials.GrayGlossy}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_FrontCamera_0.geometry}
              material-color={color}
              material={materials.FrontCamera}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_Blackmatte_0.geometry}
              material-color={color}
              material={materials.Blackmatte}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_Glass_0.geometry}
              material-color={color}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Camera2_Cameralens_0.geometry}
              material-color={color}
              material={materials.Cameralens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Screen_Wallpaper_0.geometry}
              material-color={color}
              material={materials.Wallpaper}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Apple_Logo_Logo_0.geometry}
              material-color={color}
              material={materials.Logo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CameraModule001_Glass_0.geometry}
              material-color={color}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry}
              material-color={color}
              material={materials.MicrophoneSpeaker}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.iPhone12_Pro_Body_0.geometry}
              material-color={color}
              material={materials.Body}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.VolumeButton_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PowerButton_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Port_Blackmatte_0.geometry}
              material-color={color}
              material={materials.Blackmatte}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Port_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SimTray_Blackmatte_0.geometry}
              material-color={color}
              material={materials.Blackmatte}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SimTray_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.MuteButton_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry}
              material-color={color}
              material={materials.BodyFrame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry}
              material-color={color}
              material={materials.GrayGlossy2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_Antenna_0.geometry}
              material-color={color}
              material={materials.Antenna}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry}
              material-color={color}
              material={materials.MicrophoneSpeaker}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/apple/iphone_12_pro.glb');
